common:
  img_topic: "/camera/color/image_raw"
  #lid_topic: "/livox/lidar_192_168_1_177"
  #imu_topic: "/livox/imu_192_168_1_177"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  
imu:
  init_time_seconds: 5.0      #静止时间 10
  init_imu_queue_max_size: 600   #初始化IMU队列最大长度 2000
  static_odom_pulse : 5            #静止时轮速计输出噪声
  max_static_gyro_var : 0.5      #静态下陀螺测量方差
  max_static_acce_var: 0.05     #静态下加计测量方差
  gravity_norm: 9.81           #重力大小
  use_speed_for_static_checking: false   #是否使用odom来判断车辆静止（部分数据集没有odom选项）

ndt:
  max_iteration: 4     
  voxel_size: 1.0   
  inv_voxel_size: 1.0 
  min_effective_pts: 10  
  min_pts_in_voxel: 5    
  max_pts_in_voxel: 50 
  eps: 1e-3
  res_outlier_th: 5.0 
  capacity: 100000   

eskf:
  num_iterations: 3
  quit_eps: 1e-3
  imu_dt: 0.01         
  gyro_var: 1e-5     
  acce_var : 1e-2      
  bias_gyro_var : 1e-6
  bias_acce_var : 1e-4
  update_bias_gyro : true
  update_bias_acce : true
# Lidar:

   
